### PR TITLE
feat: Add non-blocking JSON.stringify

### PR DESCRIPTION
**Pull request by HonzaMac**
This removes blocking of event-loop for large json responses.

Compressing large json response on slower hosted server causes blocking of event-loop for 950ms.

## Checklist

- [x] I have ensured my pull request is not behind the main or master branch of the original repository.
- [x] I have rebased all commits where necessary so that reviewing this pull request can be done without having to merge it first.
- [x] I have written a commit message that passes commitlint linting.
- [x] I have ensured that my code changes pass linting tests.
- [x] I have ensured that my code changes pass unit tests.
- [x] I have described my pull request and the reasons for code changes along with context if necessary.

### CODE REVIEW

**Comment by HonzaMac** [comment]
Could you take a look @3imed-jaberi ?

**Comment by 3imed-jaberi** [comment]
Hey @HonzaMac, why do you close the PR? I get the notification just now!

**Comment by HonzaMac** [comment]
I have used this implementation in our code, but it turned out to not help with blocking of event-loop. 
In our case blocking is on line 52 at index.js, which is await next().

**Comment by jonathanong** [comment]
sorry, will have to decline this PR. the module isn't used enough to be included in a core module like this. additionally, it can be easily be a downstream middleware (it's basically 1 line!) if people would like to use this. the use-case is also not common - if you're sending 1mb json responses, I have a lot of questions

**Pull request closed without merging**
